# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts




# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: brownie
      default_balance: 100000000000000000000
      # unlock: 0x12B065D77572bc9d41Aa1dd6Ee60BE70036aD968


    update_interval: 60
    verify: False

  kovan:

    verify: False
    update_interval: 60

wallets:
  from_key: ${PRIVATE_KEY}
  # You'd have to change the accounts.add to accounts.from_mnemonic to use from_mnemonic

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
